- hosts: all
  gather_facts: true
  vars_files:
      - ./yaml/variables.yaml
      - ./yaml/versions.yaml
  pre_tasks:
      - import_tasks: ./yaml/pre_tasks/setup_directory.yaml
      - import_tasks: ./yaml/pre_tasks/setup_personal.yaml
      - import_tasks: ./yaml/pre_tasks/setup_build.yaml
  tasks:
      - import_tasks: ./yaml/tasks/dotfiles.yaml
      - import_tasks: ./yaml/tasks/golang.yaml
      - import_tasks: ./yaml/tasks/rust.yaml
      - import_tasks: ./yaml/tasks/nodejs.yaml
      - import_tasks: ./yaml/tasks/php.yaml

      - import_tasks: ./yaml/tasks/common/packages.yaml
      - import_tasks: ./yaml/tasks/common/app.yaml
      - import_tasks: ./yaml/tasks/common/browser.yaml
      - import_tasks: ./yaml/tasks/common/nerdfonts.yaml
      - import_tasks: ./yaml/tasks/common/components/neovim.yaml
      - import_tasks: ./yaml/tasks/common/components/vscode.yaml
      - import_tasks: ./yaml/tasks/common/components/git.yaml

      - import_tasks: ./yaml/tasks/hyprwm/hyprland.git.yaml
      - import_tasks: ./yaml/tasks/hyprwm/clipboard.yaml
      - import_tasks: ./yaml/tasks/hyprwm/pipewire.yaml
      - import_tasks: ./yaml/tasks/hyprwm/bluetooth.yaml
      - import_tasks: ./yaml/tasks/hyprwm/packages.yaml
      - import_tasks: ./yaml/tasks/hyprwm/theme.yaml
      - import_tasks: ./yaml/tasks/hyprwm/uwsm.yaml
      - import_tasks: ./yaml/tasks/hyprwm/sddm.yaml
      - import_tasks: ./yaml/tasks/hyprwm/components/rofi.yaml
      - import_tasks: ./yaml/tasks/hyprwm/components/swaync.yaml
      - import_tasks: ./yaml/tasks/hyprwm/components/waybar.yaml
      - import_tasks: ./yaml/tasks/hyprwm/components/fcitx.yaml
      - import_tasks: ./yaml/tasks/hyprwm/components/grimblast.yaml
      - import_tasks: ./yaml/tasks/hyprwm/components/udiskie.yaml
      - import_tasks: ./yaml/tasks/hyprwm/components/tlp.yaml
      - import_tasks: ./yaml/tasks/hyprwm/components/grub.yaml
