- name: Installing common apps for Debian
  become: true
  when: ansible_facts.os_family == DEB
  ansible.builtin.apt:
      update_cache: true
      state: latest
      install_recommends: false
      name:
          - kitty
          - mpv
          - android-file-transfer
          - gparted
  tags:
      - gui_app
      - common

- name: Installing common apps for Archlinux
  become: true
  when: ansible_facts.os_family == ARCH
  community.general.pacman:
      update_cache: true
      state: latest
      name:
          - kitty
          - mpv
          - android-file-transfer
          - gparted
  tags:
      - gui_app
      - common
