- name: Installing grimblast dependencies Debian
  become: true
  when: ansible_facts.os_family == DEB
  ansible.builtin.apt:
      update_cache: true
      state: latest
      install_recommends: false
      name:
          - grim
          - slurp
          - libgtk-3-dev
          - libgtk-4-dev
          - libcairo2-dev
          - libpango1.0-dev
          - libglib2.0-dev
          - scdoc
  tags:
      - grimblast
      - hyprwm

- name: Installing grimblast dependencies Archlinux
  become: true
  when: ansible_facts.os_family == ARCH
  community.general.pacman:
      update_cache: true
      state: latest
      name:
          - grim
          - slurp
          - gtk3
          - gtk4
          - cairo
          - pango
          - glib2
          - scdoc
  tags:
      - grimblast
      - hyprwm

- name: Downloading grimblast
  ansible.builtin.git:
      repo: https://github.com/{{ item.repo }}
      dest: '{{ DOTFILES_CACHE_DIR }}/{{ item.dest }}'
      version: '{{ item.version | default(omit) }}'
      depth: 1
      recursive: true
      update: false
  loop:
      - {
            repo: hyprwm/contrib,
            dest: contrib,
            version: '{{ HYPRCONTRIB_VERSION }}',
        }
      - {repo: jtheoof/swappy, dest: swappy, version: '{{ SWAPPY_VERSION }}'}
  tags:
      - grimblast
      - hyprwm

- name: Compiling grimblast
  ansible.builtin.shell: |
      cd {{ DOTFILES_CACHE_DIR }}/contrib/grimblast
      make
  tags:
      - grimblast
      - hyprwm

- name: Installing grimblast
  become: true
  ansible.builtin.shell: |
      cd {{ DOTFILES_CACHE_DIR }}/contrib/grimblast
      make install
  tags:
      - grimblast
      - hyprwm

- name: Compiling swappy
  ansible.builtin.shell: |
      cd {{ DOTFILES_CACHE_DIR }}/swappy
      meson setup build --prefix=/usr/local
      meson compile -C build
  tags:
      - grimblast
      - hyprwm

- name: Installing swappy
  become: true
  ansible.builtin.shell: |
      cd {{ DOTFILES_CACHE_DIR }}/swappy
      meson install -C ./build
  tags:
      - grimblast
      - hyprwm
